backend:
  name: github
  repo: sekaranarumugam/operantixinsights
  branch: main

site_url: https://sekaranarumugam.github.io/operantixinsights
display_url: https://sekaranarumugam.github.io/operantixinsights

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
