backend:
  name: git-gateway
  branch: main

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
