backend:
  name: github
  repo: sekaranarumugam/operantixinsights
  branch: main

site_url: https://operantixinsights.netlify.app
display_url: https://operantixinsights.netlify.app

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Operantix Insights"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Published Date", name: "date", widget: "datetime" }
      - { label: "Content", name: "body", widget: "markdown" }
